server:
  port: 8081
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: LearnAuth
  username: root
  password: sqldb
  charset: utf8mb4
system-email:
  addr: a1337233082@163.com
  pass: mxgJG3vPG4MirYh
  host: smtp.163.com #邮件服务器
  port: 465
